---
name: Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-18.04, macos-latest]
        python-version: [3.7]
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Install dependencies on macOS
        if: startsWith(matrix.os, 'macos')
        run: |
          brew install fakeroot dpkg coreutils
          brew link --force gettext
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Python dependencies
        run: make
      - name: Check code
        run: make check
      - name: Test code
        run: make test
  tagging:
    needs: [test]
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - name: Run Buildx and deploy container
        run: make deploy
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
